
compile:
	# g++ -std=c++2a -I /usr/include/fmt -L /usr/lib/aarch64-linux-gnu hw.cpp -o hw
	# gcc -std=c++2a -I /usr/local/include/fmt -L /usr/local/lib/ -lfmt hw.cpp -o hw
	# gcc -std=c++2a -I /usr/local/include/fmt -L /usr/local/lib/ -lstdc++ hw.cpp -o hw
	g++ -std=c++2a -I /usr/local/include/fmt -L /usr/local/lib/  hw.cpp -o hw
	# g++ -std=c++2a  hw.cpp -o hw   
