FROM mcr.microsoft.com/devcontainers/cpp:ubuntu-22.04

# (Opzionale) Aggiungi gestore dipendenze, es. vcpkg
# RUN git clone https://github.com/microsoft/vcpkg.git /opt/vcpkg \
#     && /opt/vcpkg/bootstrap-vcpkg.sh

USER vscode
WORKDIR /workspaces/cpp-playground